"""Collect representative final-Pareto FFS files for field analysis.

The selection is deliberately limited to candidates generated by the six
K-RVEA optimization rounds. It contains the four single-objective extremes,
an equal-weight normalized utopia compromise, and two far-field latitude
contrasts.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]
FRONT_MEMBERS_CSV = (
    REPO_ROOT
    / "results"
    / "processed"
    / "watermelon_latitude_10deg"
    / "progression"
    / "cumulative_front_members.csv"
)
KEY_CASES_36_CSV = (
    REPO_ROOT
    / "results"
    / "processed"
    / "pareto_candidates_return_loss_gt_7db.csv"
)
OUTPUT_DIR = (
    REPO_ROOT
    / "results"
    / "processed"
    / "field_analysis"
    / "pf_ffs_selection_2026-09-07"
)
KEY_CASES_36_DIR = OUTPUT_DIR / "selected_36"

OBJECTIVE_COLUMNS = [
    "worst_s11_linear_amplitude",
    "mean_total_efficiency_linear",
    "normalized_substrate_area",
    "cap_realized_gain_linear",
]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def select_representatives(front: pd.DataFrame) -> list[tuple[str, pd.Series]]:
    selections: list[tuple[str, pd.Series]] = []

    extrema = [
        ("best_s11", "worst_s11_linear_amplitude", "min"),
        ("best_efficiency", "mean_total_efficiency_linear", "max"),
        ("smallest_area", "normalized_substrate_area", "min"),
        ("lowest_polar_cap_gain", "cap_realized_gain_linear", "min"),
        ("most_plane_directed", "plane_minus_north_mid_dB", "max"),
        ("most_midlatitude_directed", "plane_minus_north_mid_dB", "min"),
    ]
    for role, column, direction in extrema:
        index = front[column].idxmin() if direction == "min" else front[column].idxmax()
        selections.append((role, front.loc[index]))

    loss = front[OBJECTIVE_COLUMNS].astype(float).copy()
    loss["mean_total_efficiency_linear"] *= -1.0
    span = loss.max(axis=0) - loss.min(axis=0)
    normalized = (loss - loss.min(axis=0)) / span.replace(0.0, 1.0)
    distance = np.sqrt(np.square(normalized).sum(axis=1))
    selections.insert(4, ("balanced_utopia", front.loc[distance.idxmin()]))

    identities = [(str(row["source"]), str(row["case_id"])) for _, row in selections]
    if len(identities) != len(set(identities)):
        raise RuntimeError("Representative criteria selected duplicate cases.")
    return selections


def collect_key_cases_36() -> pd.DataFrame:
    key_cases = pd.read_csv(KEY_CASES_36_CSV).sort_values("candidate_rank")
    identities = key_cases[["source", "case_id"]].drop_duplicates()
    if len(key_cases) != 36 or len(identities) != 36:
        raise RuntimeError(
            "Expected exactly 36 unique rows in the prior key-case selection."
        )

    KEY_CASES_36_DIR.mkdir(parents=True, exist_ok=True)
    copied_rows: list[dict[str, object]] = []
    for _, row in key_cases.iterrows():
        source_path = Path(str(row["case_directory"])) / "Farfield Source [1].ffs"
        if not source_path.is_file():
            raise FileNotFoundError(source_path)

        source_tag = str(row["source"]).removeprefix("msabp-krvea-11var-")
        destination_name = (
            f"rank_{int(row['candidate_rank']):02d}"
            f"__{source_tag}__{row['case_id']}.ffs"
        )
        destination_path = KEY_CASES_36_DIR / destination_name
        source_hash = sha256_file(source_path)
        if destination_path.exists():
            if sha256_file(destination_path) != source_hash:
                raise RuntimeError(
                    f"Refusing to overwrite a different file: {destination_path}"
                )
        else:
            shutil.copy2(source_path, destination_path)

        record = row.to_dict()
        record.update(
            {
                "original_ffs_path": str(source_path),
                "copied_ffs_filename": destination_name,
                "ffs_sha256": source_hash,
                "ffs_size_bytes": source_path.stat().st_size,
            }
        )
        copied_rows.append(record)

    copied = pd.DataFrame(copied_rows)
    copied.to_csv(KEY_CASES_36_DIR / "selection_36.csv", index=False)
    (KEY_CASES_36_DIR / "manifest_36.json").write_text(
        json.dumps(
            {
                "created_at_utc": datetime.now(timezone.utc).isoformat(),
                "source_selection_csv": str(KEY_CASES_36_CSV),
                "selection_scope": (
                    "The previously selected 36 Pareto candidates with "
                    "return loss greater than 7 dB."
                ),
                "selection_count": len(copied),
                "files": copied_rows,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return copied


def main() -> None:
    members = pd.read_csv(FRONT_MEMBERS_CSV)
    final_stage = int(members["front_stage_order"].max())
    front = members[
        members["front_stage_order"].eq(final_stage)
        & members["sample_kind"].eq("archive")
        & members["source"].str.startswith("msabp-krvea-", na=False)
    ].copy()
    if front.empty:
        raise RuntimeError("No K-RVEA members were found on the final cumulative front.")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    selected_rows: list[dict[str, object]] = []

    for order, (role, row) in enumerate(select_representatives(front), start=1):
        source_path = Path(str(row["ffs_path"]))
        if not source_path.is_file():
            raise FileNotFoundError(source_path)

        source_short = str(row["round_label"]).lower().replace(" ", "_")
        destination_name = (
            f"{order:02d}_{role}__{source_short}__{row['case_id']}.ffs"
        )
        destination_path = OUTPUT_DIR / destination_name
        source_hash = sha256_file(source_path)
        if destination_path.exists():
            if sha256_file(destination_path) != source_hash:
                raise RuntimeError(
                    f"Refusing to overwrite a different file: {destination_path}"
                )
        else:
            shutil.copy2(source_path, destination_path)

        selected_rows.append(
            {
                "selection_order": order,
                "selection_role": role,
                "source": row["source"],
                "round_label": row["round_label"],
                "case_id": row["case_id"],
                "worst_s11_linear_amplitude": row["worst_s11_linear_amplitude"],
                "mean_total_efficiency_linear": row[
                    "mean_total_efficiency_linear"
                ],
                "normalized_substrate_area": row["normalized_substrate_area"],
                "cap_realized_gain_linear": row["cap_realized_gain_linear"],
                "cap_realized_gain_dbi": row["cap_realized_gain_dbi"],
                "plane_minus_north_mid_dB": row["plane_minus_north_mid_dB"],
                "peak_latitude_center_deg": row["peak_latitude_center_deg"],
                "original_case_directory": row["case_directory"],
                "original_ffs_path": str(source_path),
                "copied_ffs_filename": destination_name,
                "ffs_sha256": source_hash,
                "ffs_size_bytes": source_path.stat().st_size,
            }
        )

    selection = pd.DataFrame(selected_rows)
    selection.to_csv(OUTPUT_DIR / "selection.csv", index=False)
    key_cases_36 = collect_key_cases_36()

    manifest = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_front_members_csv": str(FRONT_MEMBERS_CSV),
        "final_front_stage_order": final_stage,
        "selection_scope": "Final cumulative Pareto front; K-RVEA rounds only",
        "selection_count": len(selection),
        "key_cases_36_directory": str(KEY_CASES_36_DIR),
        "key_cases_36_count": len(key_cases_36),
        "objective_directions": {
            "worst_s11_linear_amplitude": "minimize",
            "mean_total_efficiency_linear": "maximize",
            "normalized_substrate_area": "minimize",
            "cap_realized_gain_linear": "minimize",
        },
        "balanced_utopia_definition": (
            "Euclidean distance to the ideal point after independent min-max "
            "scaling of the four loss-oriented objectives on the eligible front."
        ),
        "files": selected_rows,
    }
    (OUTPUT_DIR / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    readme = """# PF FFS selection for field analysis

This folder contains seven representative members of the final cumulative
Pareto front, restricted to candidates produced by the K-RVEA optimization
rounds:

1. best worst-case S11;
2. best mean total efficiency;
3. smallest normalized substrate area;
4. lowest polar-cap realized gain;
5. equal-weight normalized four-objective utopia compromise;
6. most plane-directed member according to the latitude analysis;
7. most north-midlatitude-directed member according to the latitude analysis.

selection.csv records the four objectives, latitude metrics, original CST
case directory, original FFS path, and copied-file checksum. Put any manually
exported E-field data beside the corresponding numbered FFS file or in a
same-named subdirectory.

The selected_36 subdirectory contains all 36 previously selected key cases
with return loss greater than 7 dB. Its selection_36.csv preserves the full
parameter vectors, objective values, original paths, and copied-file checksums.
"""
    (OUTPUT_DIR / "README.md").write_text(readme, encoding="utf-8")

    display_columns = [
        "selection_order",
        "selection_role",
        "round_label",
        "case_id",
        "worst_s11_linear_amplitude",
        "mean_total_efficiency_linear",
        "normalized_substrate_area",
        "cap_realized_gain_dbi",
        "plane_minus_north_mid_dB",
        "copied_ffs_filename",
    ]
    print(selection[display_columns].to_string(index=False))
    print(f"\nPrior key cases copied: {len(key_cases_36)}")
    print(f"Key-case directory: {KEY_CASES_36_DIR}")
    print(f"\nOutput: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
